services:
- type: web
  name: netflix-cookie-bot
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: python bot.py
  envVars:
  - key: TELEGRAM_TOKEN
    sync: false
  - key: WEBHOOK_URL
    # Set this after first deploy to your service URL, e.g. https://netflix-cookie-bot.onrender.com
    sync: false
